api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import TaskApiViewSet

router_v1 = DefaultRouter()
router_v1.register(r'tasks', TaskApiViewSet)

urlpatterns = [
    path('v1/', include(router_v1.urls)),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls'))
]

tasks/urls.py
from django.urls import path

from .views import TaskListView, TaskCreateView, TaskUpdateView, TaskDeleteView

urlpatterns = [
    path('', TaskListView.as_view(), name='index'),
    path('add_tasks/', TaskCreateView.as_view(), name='add_tasks'),
    path('task/<int:pk>/', TaskUpdateView.as_view(), name='tasks_update'),
    path('delete/<int:pk>/',TaskDeleteView.as_view(), name='tasks_delete'),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import RegistrationView, UserLoginView, logout


app_name = 'users'


urlpatterns = [
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
]

tasks/models.py
from datetime import datetime
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Task(models.Model):
    """Класс Task используется для создания модели: 
    
    Attributes
    ----------
    title : CharField
        название задачи
    owner : ForeignKey
        автор задачи
    description : TextField
        описание задачи
    priority : SmallIntegerField
        приоритет задачи
    due_data : DateTimeField
        срок исполнения задачи
    completed : BooleanField
        галочка для отметки исполнения
    created_at : DateTimeField
        дата создания задачи
    updated_at : DateTimeField
        дата изменения задачи
    """
    title = models.CharField(max_length=50, verbose_name='Задача')
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='tasks', verbose_name='Автор')
    description = models.TextField(verbose_name='Описание')
    LOW = 1
    MIDDLE = 2
    HIGH = 3
    STATUSES = (
        (LOW, 'Низкий'),
        (MIDDLE, 'Средний'),
        (HIGH, 'Высокий'),
    )
    priority = models.SmallIntegerField(
        default=LOW, choices=STATUSES, verbose_name='Приоритет')
    due_data = models.DateTimeField(
        default=datetime.now, verbose_name='Срок выполнения')
    completed = models.BooleanField(default=False, verbose_name='Исполнение')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from .models import Task


class TaskListView(LoginRequiredMixin, ListView):
    """Класс для получения списка всех задач авторизованного пользователя"""

    template_name = 'tasks/index.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        return self.request.user.tasks.all()


class TaskCreateView(LoginRequiredMixin, CreateView):
    """Класс для создания задачи, передается модель Task

    Attributes
    ----------
    title : CharField
        название задачи
    description : TextField
        описание задачи
    priority : SmallIntegerField
        приоритет задачи
    due_data : DateTimeField
        срок исполнения задачи
    completed : BooleanField
        галочка для отметки исполнения
     Methods
    -------
    form_valid()
        метод устанавливает пользователя, который отправил форму, в качестве
        владельца объекта, и затем продолжает стандартную обработку формы.
    """

    model = Task
    fields = ('title', 'description', 'priority', 'due_data', 'completed')
    template_name = 'tasks/add_tasks.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        """form.instance - это экземпляр модели, который будет сохранён при
        отправке формы.

        self.request.user - это объект пользователя, который совершил запрос.
        В данном случае, мы устанавливаем пользователя, который отправил форму,
        в качестве владельца экземпляра модели.

        return super().form_valid(form) - это вызов метода form_valid базового
        класса, который продолжит обработку формы.
        """

        form.instance.owner = self.request.user
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    """Класс для изменения задачи, передается модель Task

    Attributes
    ----------
    title : CharField
        название задачи
    description : TextField
        описание задачи
    priority : SmallIntegerField
        приоритет задачи
    due_data : DateTimeField
        срок исполнения задачи
    completed : BooleanField
        галочка для отметки исполнения
    """

    model = Task
    fields = ('title', 'description', 'priority', 'due_data', 'completed')
    template_name_suffix = "s_update"
    success_url = reverse_lazy('index')


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    """Класс для удаления задачи, передается модель Task

    Methods
    -------
    get_object()
        метод позволяет удалять задачу только автору этой задачи
    """
    model = Task
    success_url = reverse_lazy('index')

    def get_object(self, queryset=None):
        """super(TaskDeleteView, self).get_object(queryset) - вызывает метод 
        get_object базового класса для получения объекта задачи, который 
        должен быть удалён.

        if Task.owner != self.request.user: - проверяет, является ли текущий 
        пользователь (self.request.user) владельцем задачи (Task.owner).

        raise Http404("Вы не можете удалить данную задачу") - вызывается 
        исключение Http404, которое приводит к отображению страницы 404 с 
        сообщением, что пользователь не может удалить задачу.

        return Task - если проверка пройдена, метод возвращает объект задачи 
        для дальнейшего удаления.
        """

        Task = super(TaskDeleteView, self).get_object(queryset)
        if Task.owner != self.request.user:
            raise Http404("Вы не можете удалить данную категорию")
        return Task

templates/tasks/add_tasks.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>Добавление задачи</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f7f7f7;
            font-family: 'Arial', sans-serif;
        }

        form {
            border: 1px solid #dedede;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background-color: #ffffff;
            width: 300px;
        }

        label,
        input,
        textarea {
            display: block;
            width: 100%;
            margin-bottom: 10px;
        }

        input,
        textarea {
            border: 1px solid #ccc;
            border-radius: 4px;
            padding: 8px;
        }

        input[type="submit"] {
            background-color: #0051ff;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #0509db;
        }
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }

        .btn-primary:hover {
            background-color: white;
            color: black;
            border: 2px solid #007bff;
        }
    </style>
</head>

<body>
    <div class="container">
        <form method="post" novalidate class="card" action="{% url 'add_tasks' %}">
            {% csrf_token %}
            <div class="form-group">
                <div class="form-group">
                    {{ form.as_p }}
                </div>
            </div>
            <input type="submit" value="Добавить">
            <a href="{% url 'index' %}" class="btn btn-primary">Назад</a>
        </form>
    
    
</body>

</html>

templates/tasks/index.html
<!-- index.html -->
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Задачи</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .task-card {
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 20px;
            margin: 10px auto;
            max-width: 600px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .task-card h2 {
            color: #333;
            margin-bottom: 10px;
        }

        .task-card p {
            color: #666;
            line-height: 1.6;
        }

        .task-card p strong {
            color: #333;
        }

        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }

        .btn-primary:hover {
            background-color: white;
            color: black;
            border: 2px solid #007bff;
        }
    </style>
</head>

<body>
    <div style="text-align: center; margin-top: 20px;">
        <a href="{% url 'add_tasks' %}" class="btn btn-primary">Создать задачу</a>
        <a href="{% url 'users:logout' %}" class="btn btn-primary">Выйти</a>
    </div>
    {% for task in tasks %}
    <div class="task-card">
        <h2>{{ task.title }}</h2>
        <p><strong>Описание:</strong> {{ task.description }}</p>
        <p><strong>Автор:</strong> {{ task.owner }}</p>
        <p><strong>Срок выполнения:</strong> {{ task.due_data }}</p>
        <p><strong>Приоритет:</strong> {{ task.get_priority_display }}</p>
        <p><strong>Исполнение:</strong> {{ task.completed|yesno:"Да,Нет" }} <input type="checkbox" name="completed" {% if task.completed %}checked{% endif %} disabled></p>
        <p><strong>Дата создания:</strong> {{ task.created_at }}</p>
        <p><strong>Дата изменения:</strong> {{ task.updated_at }}</p>
        <a href="{% url 'tasks_update' task.id %}" class="btn btn-primary">Редактировать задачу</a>
        <form method="post" action="{% url 'tasks_delete' pk=task.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" onclick="return confirm('Вы уверены, что хотите удалить эту запись?')">Удалить</button>
        </form>
    </div>
    {% endfor %}
</body>

</html>

templates/tasks/tasks_update.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        form {
            max-width: 500px;
            margin: 20px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }

        label {
            display: block;
            margin-top: 10px;
        }

        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        input[type="checkbox"] {
            margin-top: 5px;
        }

        input[type="submit"] {
            background-color: #007bff;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            float: right;
        }

        input[type="submit"]:hover {
            background-color: #007bff;
        }

        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }

        .btn-primary:hover {
            background-color: white;
            color: black;
            border: 2px solid #007bff;
        }
    </style>
</head>

<body>
    <form method="post" action="{% url 'tasks_update' task.id %}">
        <form method="post">{%csrf_token%}{{form.as_p}}<inputtype="submit"value="Update"></form>
        <input type="submit" value="Сохранить изменения">
        <a href="{% url 'index' %}" class="btn btn-primary">Назад</a>
    </form>

</body>

</html>